### ISSUE TITLE
how to fetch external ip from openfaas release ?

### ISSUE THREAD

**Issue by pascally** [dafriedmann/aks-openfaas-terraform#1]
hi, i would like to know if there s a simple way to fetch the external ip of openfaas (when setting property serviceType to LoadBalancer) and put it in an output ?

**Comment by dafriedmann** [comment]
Hi! Sorry for the very late response, unfortunately I did not get a notification on this issue :/.
You can view the public ip of the external gateway by looking at the k8-Dashboard.
Or give: ```kubectl describe svc openfaas/gateway  | grep IP``` a try.
